language: ruby

rvm:
  - 2.2

branches:
  only:
    - master
    - release

before_install:
  - npm install -g gulp

install:
  - npm install
  - bundle install

cache:
  directories:
    -node_modules

before_script:
  - echo -e "Host 104.130.157.215\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - jekyll build
  - gulp build

after_success:
  - bash deploy.sh
