# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Bavaria Yachts USA
description: 
tagline: 
url: 

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist

keep_files: ['assets']

# general setting for Jekyll

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true

source: src
destination: dist

exclude: ['wp-theme']
keep_files: ['news']

# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
paginate: 3
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

gems: [jekyll-paginate]

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']

highlighter: true

defaults:
  - 
    scope:
      path: ""
      type: posts
    values:
      layout: default
